In [4]:
import numpy
def quicksort(arr):
    if len(arr) <= 1:
      return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)
print(quicksort([3,6,8,10,1,2,1]))
# Prints "[1, 1, 2, 3, 6, 8, 10]"

[1, 1, 2, 3, 6, 8, 10]


In [8]:
import numpy as np
# We wiLl add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 9, 1])
y = np.empty_like(x)  # Create an empty matrix with the same shape as x
# Add the vector v to each row of the matrix x with an explicit Loop
for i in range(4):
    y[i, :] = x[i, :] + v
# Now y 1s the following
#f[2 2 4]
# [5 5 7]
# [8 8 160]
# [11 11 13]]
print(y)

[[ 2 11  4]
 [ 5 14  7]
 [ 8 17 10]
 [11 20 13]]


In [10]:
import numpy as np
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 8, 1])
vv = np.tile(v, (4, 1)) # Stack 4 copies of v on top of each other
print(vv) # Prints "[[1 @ 1]
# [1 @1]
# [1 @1]
if [1 @ 1]]:
  y=x+vv_ # Add x and vv elementwise
print(y) # Prints "[[ 2 2 4
#t [5 5 7]
# [8 8 10]
# [11 11 13]]"

SyntaxError: ignored

In [45]:
!pip install scipy==1.1.0



     |████████████████████████████████| 31.2MB 133kB/s 
ERROR: pymc3 3.11.2 has requirement scipy>=1.2.0, but you'll have scipy 1.1.0 which is incompatible.
ERROR: plotnine 0.6.0 has requirement scipy>=1.2.0, but you'll have scipy 1.1.0 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
  Found existing installation: scipy 1.4.1
    Uninstalling scipy-1.4.1:
      Successfully uninstalled scipy-1.4.1


In [48]:
#scipy.misc
#scipy.misc.imread
#from scipy.misc import imread
import scipy.misc
import numpy as np
#import imageio
#image = imageio.imread('pic.png')
# Read an JPEG image into a numpy array
img =   scipy.misc.imread('/content/sample_data/cat.jpg' )
print(img.dtype, img.shape) # Prints "“uint8 (400, 248, 3)"
# We can tint the twmage by scaling each of the color channels
# by a different scalar constant. The image has shape (400, 248, 3);
# we multiply it by the array [1, 9.95, 8.9] of shape (3,);
# numpy broadcasting means that this Leaves the red channel unchanged,
# and multiplies the green and blue channels by @.95 and @.9
# respectively.
img_tinted = img * [1, 0.95, 0.9]
# Resize the tinted image to be 300 by 300 pixels.
img_tinted = imresize(img_tinted, (300, 300))
# Write the tinted image back to disk
imsave( "/content/sample_data/cat_tinted.jpg",img_tinted) 
imshow(img_tinted)

AttributeError: ignored